### PR TITLE
Add netlify badge to readme

### PR DESCRIPTION
**Pull request by vikr01**

### CODE REVIEW

**Comment by amilajack** [comment]
Is there a more normal looking badge? This one looks kinda weird 😂

**Comment by vikr01** [comment]
@amilajack Nope, unfortunately. Tracking badges/shields#3129.

**Comment by amilajack** [comment]
[Netlify Status](https://app.netlify.com/sites/gitwriter/deploys)

This is our badge. See https://github.com/badges/shields/issues/3129#issuecomment-470032754

**Comment by vikr01** [comment]
@amilajack Sure, we can use that but note that it's unofficial.

**Comment by amilajack** [comment]
>  we can use that but note that it's unofficial.

Yea I saw that. We can change later when https://github.com/badges/shields/pull/3178 gets merged

**Pull request merged**
